name: Automatic Release
author: Trinovantes
description: Automatically creates a GitHub release with ChangeLog

inputs:
  auto_release_tag:
    description: Git tag (for automatic release)
    required: false
  auto_release_title:
    description: Release title (for automatic release)
    required: false
  is_draft:
    description: Should this release be marked as a draft?
    required: false
    default: 'false'
  is_prerelease:
    description: Should this release be marked as a pre-release?
    required: false
    default: 'true'
  branch:
    description: Git branch
    required: false
    default: 'master'

outputs:
  tag:
    description: The release tag this action just created/updated
    value: ${{ steps.main.outputs.tag }}
  prev_tag:
    description: The release tag this action just upgraded from
    value: ${{ steps.main.outputs.prev_tag }}
  release_id:
    description: The id of the release this action just created
    value: ${{ steps.main.outputs.release_id }}
  upload_url:
    description: The upload url of the release this action just created
    value: ${{ steps.main.outputs.upload_url }}

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2

    - run: |-
        cd "${{ github.action_path }}"
        bun install
        cd -
      shell: bash

    - id: main
      run: bun run "${{ github.action_path }}/src/main.ts"
      shell: bash
      env:
        auto_release_tag: ${{ inputs.auto_release_tag }}
        auto_release_title: ${{ inputs.auto_release_title }}
        is_draft: ${{ inputs.is_draft }}
        is_prerelease: ${{ inputs.is_prerelease }}
        branch: ${{ inputs.branch }}
