name: Automatic Release
author: Trinovantes
description: Automatically creates a release
inputs:
  title:
    description: Release title (for automatic release)
    required: false
  automatic_release_tag:
    description: Git tag (for automatic release)
    required: false
  is_draft:
    description: Should this release be marked as a draft?
    required: false
    default: false
  is_prerelease:
    description: Should this release be marked as a pre-release?
    required: false
    default: true
outputs:
  tag:
    description: The release tag this action just created/updated
  prev_tag:
    description: The release tag this action just upgraded from
  release_id:
    description: The id of the release this action just created
  upload_url:
    description: The upload url of the release this action just created
runs:
  using: node12
  main: dist/index.js
